[project]
name = "nft-shop"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.nft-trait]
path = "contracts/nft-trait.clar"

[contracts.shop]
path = "contracts/shop.clar"

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"

[contracts.bogus-nft]
path = "contracts/sip009-nft.clar"

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"

[contracts.bogus-ft]
path = "contracts/sip010-ft-trait.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
