[project]
name = "nft-shop"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.010-token-trait]
path = "contracts/010-token-trait.clar"

[contracts.nft-trait]
path = "contracts/nft-trait.clar"

[contracts.shop]
path = "contracts/shop.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
